os: linux
dist: xenial
language: python

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - g++-9

env:
  global:
  - CXX=g++-9 CC=gcc-9 GCOV=gcov-9
  - RUN_LINTER=1
  - BUILD_DOCS=

stages:
  - tests

matrix:
  include:
    - stage: tests
      language: python
      name: "Unit Tests Instrumenter"
      python: 3.7
      install:
        - pip install --upgrade pytest pytest-cov lxml jinja2
      before_script:
        - cd tests/instrumenter
      script:       
        - python3 -m pytest --cov=./

    - language: python
      name: "Style check Instrumenter"
      python: 3.7
      install:
        - pip install --upgrade flake8
      before_script:
        - cd src/instrumenter
      script:
        - python3 -m flake8 --ignore=E501

    - language: python
      name: "Unit Tests Analyzer"
      python: 3.7
      install:
        - pip install --upgrade pytest pytest-cov lxml jinja2
      before_script:
        - cd tests/analyzer
      script:
        - python3 -m flake8 --ignore=E501
        - python3 -m pytest --cov=./

    - language: python
      name: "Style check Analyzer"
      python: 3.7
      install:
        - pip install --upgrade flake8
      before_script:
        - cd src/analyzer
      script:
        - python3 -m flake8 --ignore=E501

    - language: ruby
      name: "Unit Tests Runtime Helper"
      rvm: 2.6
      install:
        - gem install ceedling
      before_script:
        - cd tests/runtime_helper
      script:
        - ceedling clobber gcov:all

    - language: python
      name: "Style check Runtime Helper"
      python: 3.7
      install:
        - pip install --upgrade cpplint
      before_script:
        - cd src/runtime_helper
      script:
        - cpplint --linelength=100 codeconut_helper.c codeconut_helper.h
    
after_success:
  - bash <(curl -s https://codecov.io/bash)