os: linux
dist: xenial
language: python

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-9
    - g++-9

env:
  global:
  - CXX=g++-9 CC=gcc-9 GCOV=gcov-9
  - RUN_LINTER=1
  - BUILD_DOCS=

stages:
  - tests

matrix:
  include:
    - stage: tests
      language: python
      name: "Unit Tests Instrumenter"
      python: 3.7
      install:
        - pip install --upgrade pytest pytest-cov lxml jinja2
      before_script:
        - pip install -e .
        - cd coveron_instrumenter
      script:
        - python3 -m pytest --cov=./

    allow_failures:
      - language: python
        name: "Style check Instrumenter"
        python: 3.7
        install:
          - pip install --upgrade flake8
        before_script:
          - cd coveron_instrumenter
        script:
          - python3 -m flake8 --ignore=E501,F405,W503 --exclude tests,clang

    - language: ruby
      name: "Unit Tests Runtime Helper"
      rvm: 2.6
      install:
        - gem install ceedling
      before_script:
        - cd coveron_instrumenter/coveron_runtime_helper
      script:
        - ceedling clobber gcov:all

    allow_failures:
      - language: python
        name: "Style check Runtime Helper"
        python: 3.7
        install:
          - pip install --upgrade cpplint
        before_script:
          - cd coveron_instrumenter/coveron_runtime_helper/src
        script:
          - cpplint coveron_helper.c coveron_helper.h
    
after_success:
  - bash <(curl -s https://codecov.io/bash)